---
title: "Data cleaning - chl 2024"
output: html_document
date: "2025-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#prep data
library(readxl)
library(tidyverse)
library(dplyr)
library(plotrix)
library(lubridate)
library(zoo)
Chl24Data <- read_excel("C:/Users/sellkes/Documents/GitHub/Dotson_SURE_Kelp_Nutrients/Data/Chl-a_Field_2024_2025-08-26_CEG.xlsx") # you will have to change the directory to where you saved the file, then you should be able to upload
Chl24Data <- Chl_a_Field_2024_2025_08_26_CEG
as.Date(Chl24Data$Date, format="%Y-%m-%d")
Chl24Data$month <- format(Chl24Data$Date, '%m')
Chl24Data$YearMonth <- as.yearmon(Chl24Data$Date)
names(Chl24Data)[4] <- 'chlorophyll'
Chl24Data$Week <- strftime(Chl24Data$Date, format = "%V")
Chl24Data$year <- format(Chl24Data$Date, '%y')



Chl24Data <- Chl24Data %>%
  mutate(cape = case_when(
   SiteCode %in% c('FC', 'BB') ~ 'Foulweather',   # Assign 'Foulweather' for FC and BB
    SiteCode %in% c('SH', 'YB', 'TK') ~ 'Perpetua', # Assign 'Perpetua' for SH, YB, and TK
   SiteCode %in% c('CB', 'RP') ~ 'Blanco',        # Assign 'Blanco' for CB and RP
    TRUE ~ 'Unknown'                           # For any other site, assign 'Unknown'
  ))



Chl24DataAverages <- Chl24Data %>%
  group_by(YearMonth, SiteCode) %>%
  summarise(average_chl = mean(chlorophyll),
            Week = Week, cape = cape, year =year)

Chl24DataAverages$YearMonthSite <- paste(Chl24DataAverages$YearMonth, Chl24DataAverages$SiteCode, sep="_")
Chl24DataAverages$WeekYearSite <- paste(Chl24DataAverages$Week, Chl24DataAverages$year, Chl24DataAverages$SiteCode, sep="_")


write.csv(Chl24DataAverages, file = "C:/Users/sellkes/Documents/GitHub/Dotson_SURE_Kelp_Nutrients/Data/Chlorophyll_data_fieldfluro_clean.csv") # you'll also have to fix the folder you're saving to since this is to my computer - i can show you later
```

