---
title: "Data Cleaning - Kelp"
output: html_document
date: "2025-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#prep data
library(readxl)
library(tidyverse)
library(dplyr)
library(plotrix)
library(lubridate)
library(zoo)
MasterData <- Master_Data_Sheet_KRC_1_All
MasterData <- read_excel("C:/Users/sellkes/Documents/GitHub/Dotson_SURE_Kelp_Nutrients\Data\Master_Data_Sheet_KRC_1_All.xlsx) # you will have to change the directory to where you saved the file, then you should be able to upload
as.Date(MasterData$Date, format="%Y-%d-%m")
names(MasterData)[2] <- 'site'
names(MasterData)[7] <- 'recruits'
names(MasterData)[4] <- 'transect'
MasterData$PlotID <- paste(MasterData$site, MasterData$transect, MasterData$`Meter #`, sep = ".")

Transect_Avg <- MasterData %>%
  group_by(Date, Species, site, transect) %>%
  summarise(average_value = mean(recruits)) 

Transect_Avg$Week <- strftime(Transect_Avg$Date, format = "%V")
Transect_Avg$month <- format(Transect_Avg$Date, '%m')
Transect_Avg$year <- format(Transect_Avg$Date, '%y')
Transect_Avg$YearMonth <- as.yearmon(Transect_Avg$Date)
Transect_Avg$YearMonthSite <- paste(Transect_Avg$YearMonth, Transect_Avg$site, sep="_")
Transect_Avg$WeekYearSite <- paste(Transect_Avg$Week, Transect_Avg$year, Transect_Avg$site, sep="_")

Transect_Avg <- Transect_Avg %>%
  mutate(cape = case_when(
    site %in% c('FC', 'BB') ~ 'Foulweather',   # Assign 'Foulweather' for FC and BB
    site %in% c('SH', 'YB', 'TK') ~ 'Perpetua', # Assign 'Perpetua' for SH, YB, and TK
    site %in% c('CB', 'RP') ~ 'Blanco',        # Assign 'Blanco' for CB and RP
    TRUE ~ 'Unknown'                           # For any other site, assign 'Unknown'
  ))

?reframe
#save the transect average dataframe 
write.csv(Transect_Avg, file = ".//Kelp_Averages_Clean.csv")
```

```{r}
?left_join
#join dataframes (make sure you've done the chlorophyll one first)
chlData_new <- read.csv(".//Chlorophyll_data_fieldfluro_clean.csv")
chlData <- Chlorophyll_data_fieldfluro_clean
KelpData <- read.csv(".//Kelp_Averages_Clean.csv")
Combined_Data_month <- left_join(KelpData, chlData, by = "YearMonthSite" )
Combined_Data_Week <- left_join(KelpData, chlData, by = "WeekYearSite" )
Combined_Data_month <- Combined_Data_month[complete.cases(Combined_Data_month),]
Combined_Data_Week<-  Combined_Data_Week[complete.cases(Combined_Data_Week),]

write.csv(Combined_Data_month, file = "Kelp_Chl_Monthly.csv")
write.csv(Combined_Data_Week, file = "Kelp_Chl_Weekly.csv")

```


